#!bash -uvx
gcc -I/usr/include/subversion-1 -I/usr/include/apr-1 minimal_client.c    -llibapr-1 -lsvn_client-1 -lsvn_fs_util-1 -lsvn_ra_serf-1 -lsvn_subr-1 -lsvn_wc-1 -lsvn_delta-1 -lsvn_fs_x-1 -lsvn_ra_svn-1 -lsvn_swig_perl-1 -lsvn_diff-1 -lsvn_fs-1 -lsvn_ra-1 -lsvn_swig_py-1 -lsvn_fs_fs-1 -lsvn_ra_local-1 -lsvn_repos-1 -lsvn_swig_ruby-1
./a.exe https://github.com/cppcommons/d-sample/trunk
